//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>лейтенанта ПЕТРУШКОВА К.В., младшего референта 1 отделения 2 отдела</string>
  <string>капитана УШАНСКОГО А.А., старшего инженера 3 отделения 4 отдела</string>
  <string>лейтенанта КИСКОВА Е.П., младшего референта 5 отделения 6 отдела</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Persons {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Persons"]));
            }
            set {
                this["Persons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>майору МОЛОТКО А.А., начальнику смены комендантского отделения</string>
  <string>старшему прапорщику ЯКОВУ А.В., помощнику дежурного коменданта 1 категории комендантского отделения</string>
  <string>прапорщику ГРИГОРЬЕВОЙ Г.В., помощнику дежурного коменданта 2 категории комендантского отделения</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Comendas {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Comendas"]));
            }
            set {
                this["Comendas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>дежурным по Центру</string>
  <string>заместителем дежурного по Центру</string>
  <string>дежурным по посту №1</string>
  <string>помощником дежурного по посту №1</string>
  <string>дежурным по посту №2</string>
  <string>помощником дежурного по посту №2</string>
  <string>дежурным по гаражу с 08:00 до 20:00 часов</string>
  <string>дежурным оператором ТСО с 08:00 до 20:00 часов</string>
  <string>дежурным по контрольно-обходному посту с 08:00 до 20:00 часов</string>
  <string>помощником дежурного по контрольно-обходному посту с 08:00 до 20:00 часов</string>
  <string>дежурным оператором ТСО с 20:00 до 08:00 часов</string>
  <string>дежурным по контрольно-обходному посту с 20:00 до 08:00 часов</string>
  <string>помощником дежурного по контрольно-обходному посту с 20:00 до 08:00 часов</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Outfits {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Outfits"]));
            }
            set {
                this["Outfits"] = value;
            }
        }
    }
}
